[build]
  command = "npm run production"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/models/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"